"""create initial database schema

Revision ID: 3e373c7daf66
Revises: 
Create Date: 2026-07-17 13:20:57.367418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e373c7daf66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS ingestion"))
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS core"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_unit', sa.String(length=30), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            value_type IN (\n                'numeric',\n                'text',\n                'boolean',\n                'categorical'\n            )\n            ", name=op.f('ck_exam_types_value_type_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_types')),
    sa.UniqueConstraint('code', name=op.f('uq_exam_types_code')),
    schema='core'
    )
    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_code', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('biological_sex', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            biological_sex IS NULL\n            OR biological_sex IN (\n                'female',\n                'male',\n                'intersex',\n                'unknown',\n                'not_informed'\n            )\n            ", name=op.f('ck_patients_biological_sex_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('external_code', name=op.f('uq_patients_external_code')),
    schema='core'
    )
    op.create_table('data_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            source_type IN (\n                'csv',\n                'json',\n                'api',\n                'database',\n                'spreadsheet',\n                'synthetic',\n                'public'\n            )\n            ", name=op.f('ck_data_sources_source_type_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_data_sources_name')),
    schema='ingestion'
    )
    op.create_table('biological_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sample_code', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('sample_type', sa.String(length=30), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            sample_type IN (\n                'blood',\n                'serum',\n                'plasma',\n                'saliva',\n                'urine',\n                'tissue',\n                'other'\n            )\n            ", name=op.f('ck_biological_samples_sample_type_allowed')),
    sa.CheckConstraint('\n            received_at IS NULL\n            OR received_at >= collected_at\n            ', name=op.f('ck_biological_samples_received_after_collection')),
    sa.ForeignKeyConstraint(['patient_id'], ['core.patients.id'], name=op.f('fk_biological_samples_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biological_samples')),
    sa.UniqueConstraint('sample_code', name=op.f('uq_biological_samples_sample_code')),
    schema='core'
    )
    op.create_index(op.f('ix_biological_samples_patient_id'), 'biological_samples', ['patient_id'], unique=False, schema='core')
    op.create_table('laboratory_exams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('exam_type_id', sa.BigInteger(), nullable=False),
    sa.Column('sample_id', sa.BigInteger(), nullable=True),
    sa.Column('data_source_id', sa.BigInteger(), nullable=False),
    sa.Column('external_exam_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='registered', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            status IN (\n                'registered',\n                'processing',\n                'completed',\n                'cancelled'\n            )\n            ", name=op.f('ck_laboratory_exams_status_allowed')),
    sa.CheckConstraint('\n            performed_at IS NULL\n            OR requested_at IS NULL\n            OR performed_at >= requested_at\n            ', name=op.f('ck_laboratory_exams_performed_after_requested')),
    sa.ForeignKeyConstraint(['data_source_id'], ['ingestion.data_sources.id'], name=op.f('fk_laboratory_exams_data_source_id_data_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_type_id'], ['core.exam_types.id'], name=op.f('fk_laboratory_exams_exam_type_id_exam_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['core.patients.id'], name=op.f('fk_laboratory_exams_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sample_id'], ['core.biological_samples.id'], name=op.f('fk_laboratory_exams_sample_id_biological_samples'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_laboratory_exams')),
    sa.UniqueConstraint('data_source_id', 'external_exam_code', name='uq_laboratory_exams_source_external_code'),
    schema='core'
    )
    op.create_index(op.f('ix_laboratory_exams_data_source_id'), 'laboratory_exams', ['data_source_id'], unique=False, schema='core')
    op.create_index(op.f('ix_laboratory_exams_exam_type_id'), 'laboratory_exams', ['exam_type_id'], unique=False, schema='core')
    op.create_index(op.f('ix_laboratory_exams_patient_id'), 'laboratory_exams', ['patient_id'], unique=False, schema='core')
    op.create_index(op.f('ix_laboratory_exams_sample_id'), 'laboratory_exams', ['sample_id'], unique=False, schema='core')
    op.create_table('exam_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('laboratory_exam_id', sa.BigInteger(), nullable=False),
    sa.Column('result_code', sa.String(length=50), nullable=False),
    sa.Column('result_value_numeric', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('result_value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n                result_value_numeric IS NOT NULL\n                AND result_value_text IS NULL\n            )\n            OR\n            (\n                result_value_numeric IS NULL\n                AND result_value_text IS NOT NULL\n            )\n            ', name=op.f('ck_exam_results_exactly_one_result_value')),
    sa.ForeignKeyConstraint(['laboratory_exam_id'], ['core.laboratory_exams.id'], name=op.f('fk_exam_results_laboratory_exam_id_laboratory_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_results')),
    sa.UniqueConstraint('laboratory_exam_id', 'result_code', name='uq_exam_results_exam_result_code'),
    schema='core'
    )
    op.create_index(op.f('ix_exam_results_laboratory_exam_id'), 'exam_results', ['laboratory_exam_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_results_laboratory_exam_id'), table_name='exam_results', schema='core')
    op.drop_table('exam_results', schema='core')
    op.drop_index(op.f('ix_laboratory_exams_sample_id'), table_name='laboratory_exams', schema='core')
    op.drop_index(op.f('ix_laboratory_exams_patient_id'), table_name='laboratory_exams', schema='core')
    op.drop_index(op.f('ix_laboratory_exams_exam_type_id'), table_name='laboratory_exams', schema='core')
    op.drop_index(op.f('ix_laboratory_exams_data_source_id'), table_name='laboratory_exams', schema='core')
    op.drop_table('laboratory_exams', schema='core')
    op.drop_index(op.f('ix_biological_samples_patient_id'), table_name='biological_samples', schema='core')
    op.drop_table('biological_samples', schema='core')
    op.drop_table('data_sources', schema='ingestion')
    op.drop_table('patients', schema='core')
    op.drop_table('exam_types', schema='core')
    # ### end Alembic commands ###

    op.execute(sa.text("DROP SCHEMA IF EXISTS core"))
    op.execute(sa.text("DROP SCHEMA IF EXISTS ingestion"))
