"""add ETL lineage and staging

Revision ID: 97a13d478cb4
Revises: 3e373c7daf66
Create Date: 2026-08-06 11:27:49.725310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97a13d478cb4'
down_revision: Union[str, Sequence[str], None] = '3e373c7daf66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        sa.text(
            "CREATE SCHEMA IF NOT EXISTS staging"
        )
    )

    op.execute(
        sa.text(
            "CREATE SCHEMA IF NOT EXISTS quality"
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_source_id', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_source_files_size_bytes_non_negative')),
    sa.ForeignKeyConstraint(['data_source_id'], ['ingestion.data_sources.id'], name=op.f('fk_source_files_data_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_files')),
    sa.UniqueConstraint('data_source_id', 'sha256', name='uq_source_files_source_sha256'),
    schema='ingestion'
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.BigInteger(), nullable=False),
    sa.Column('duplicate_of_run_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=40), server_default='running', nullable=False),
    sa.Column('pipeline_name', sa.String(length=100), server_default='patient_csv', nullable=False),
    sa.Column('pipeline_version', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('valid_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rejected_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('inserted_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('existing_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('acceptance_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('processed_file_path', sa.Text(), nullable=True),
    sa.Column('rejection_file_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'running'\n                AND finished_at IS NULL\n            )\n            OR\n            (\n                status <> 'running'\n                AND finished_at IS NOT NULL\n            )\n            ", name=op.f('ck_ingestion_runs_finished_at_matches_status')),
    sa.CheckConstraint("\n            status IN (\n                'running',\n                'completed',\n                'completed_with_rejections',\n                'failed',\n                'skipped_duplicate'\n            )\n            ", name=op.f('ck_ingestion_runs_status_allowed')),
    sa.CheckConstraint('\n            acceptance_rate >= 0\n            AND acceptance_rate <= 100\n            ', name=op.f('ck_ingestion_runs_acceptance_rate_range')),
    sa.CheckConstraint('\n            received_count >= 0\n            AND valid_count >= 0\n            AND rejected_count >= 0\n            AND inserted_count >= 0\n            AND existing_count >= 0\n            ', name=op.f('ck_ingestion_runs_counts_non_negative')),
    sa.CheckConstraint('received_count = valid_count + rejected_count', name=op.f('ck_ingestion_runs_received_matches_quality_counts')),
    sa.CheckConstraint('valid_count = inserted_count + existing_count', name=op.f('ck_ingestion_runs_valid_matches_load_counts')),
    sa.ForeignKeyConstraint(['duplicate_of_run_id'], ['ingestion.ingestion_runs.id'], name=op.f('fk_ingestion_runs_duplicate_of_run_id_ingestion_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['ingestion.source_files.id'], name=op.f('fk_ingestion_runs_source_file_id_source_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs')),
    sa.UniqueConstraint('run_uuid', name=op.f('uq_ingestion_runs_run_uuid')),
    schema='ingestion'
    )
    op.create_table('patient_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_record', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_external_code', sa.String(length=50), nullable=True),
    sa.Column('normalized_birth_date', sa.Date(), nullable=True),
    sa.Column('normalized_biological_sex', sa.String(length=20), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            validation_status IN (\n                'valid',\n                'rejected'\n            )\n            ", name=op.f('ck_patient_records_validation_status_allowed')),
    sa.CheckConstraint('source_row_number >= 2', name=op.f('ck_patient_records_source_row_after_header')),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion.ingestion_runs.id'], name=op.f('fk_patient_records_ingestion_run_id_ingestion_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['core.patients.id'], name=op.f('fk_patient_records_patient_id_patients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_records')),
    sa.UniqueConstraint('ingestion_run_id', 'source_row_number', name='uq_patient_records_run_row'),
    schema='staging'
    )
    op.create_table('data_quality_issues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('staged_record_id', sa.BigInteger(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staged_record_id'], ['staging.patient_records.id'], name=op.f('fk_data_quality_issues_staged_record_id_patient_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_issues')),
    schema='quality'
    )
    op.create_index(op.f('ix_source_files_data_source_id'), 'source_files', ['data_source_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_runs_duplicate_of_run_id'), 'ingestion_runs', ['duplicate_of_run_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_runs_source_file_id'), 'ingestion_runs', ['source_file_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_patient_records_ingestion_run_id'), 'patient_records', ['ingestion_run_id'], unique=False, schema='staging')
    op.create_index(op.f('ix_patient_records_patient_id'), 'patient_records', ['patient_id'], unique=False, schema='staging')
    op.create_index(op.f('ix_data_quality_issues_code'), 'data_quality_issues', ['code'], unique=False, schema='quality')
    op.create_index(op.f('ix_data_quality_issues_staged_record_id'), 'data_quality_issues', ['staged_record_id'], unique=False, schema='quality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_quality_issues_staged_record_id'), table_name='data_quality_issues', schema='quality')
    op.drop_index(op.f('ix_data_quality_issues_code'), table_name='data_quality_issues', schema='quality')
    op.drop_table('data_quality_issues', schema='quality')
    op.drop_index(op.f('ix_patient_records_patient_id'), table_name='patient_records', schema='staging')
    op.drop_index(op.f('ix_patient_records_ingestion_run_id'), table_name='patient_records', schema='staging')
    op.drop_table('patient_records', schema='staging')
    op.drop_index(op.f('ix_ingestion_runs_source_file_id'), table_name='ingestion_runs', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_runs_duplicate_of_run_id'), table_name='ingestion_runs', schema='ingestion')
    op.drop_table('ingestion_runs', schema='ingestion')
    op.drop_index(op.f('ix_source_files_data_source_id'), table_name='source_files', schema='ingestion')
    op.drop_table('source_files', schema='ingestion')
    # ### end Alembic commands ###

    op.execute(
        sa.text(
            "DROP SCHEMA IF EXISTS quality"
        )
    )

    op.execute(
        sa.text(
            "DROP SCHEMA IF EXISTS staging"
        )
    )
